/**
 * Studio Content Data
 * 
 * This file contains all content items for the Studio monitor tower.
 * Each item will be displayed on a monitor in the tower.
 * 
 * Platforms: 'clients', 'github', 'skills'
 */

export const PLATFORM_CONFIG = {
    clients: {
        color: '#EA4B71',
        accentColor: '#c0365a',
        icon: '💼',
        label: 'Clients',
        shape: 'tv', // Wide CRT style
    },
    github: {
        color: '#238636',
        accentColor: '#1a6b2b',
        icon: '⌨️',
        label: 'GitHub',
        shape: 'monitor', // Thin desktop monitor
    },
    skills: {
        color: '#6366F1',
        accentColor: '#4F46E5',
        icon: '🧠',
        label: 'Skills',
        shape: 'phone', // Vertical phone
    },
};

// Each item gets its own unique front texture
export const CONTENT_DATA = [
    // ============ CLIENT PROJECTS (TV Monitors) ============
    {
        id: 'cl-001',
        platform: 'clients',
        title: 'Genius PR — AI Outreach Automation',
        description: 'Multi-workflow n8n outreach automation for a PR agency. HubSpot, HeyReach, Instantly, Claude AI — all integrated. Reply classification, meeting booking, full pipeline.',
        frontTexture: '/textures/studio/tv_cl-001.webp',
        paintedFrontTexture: '/textures/studio/tv_cl-001_painted.webp',
        thumbnail: null,
        url: 'https://www.linkedin.com/in/muhammad-umer-1bb52326b',
        date: '2026-03-28',
        views: 'n8n',
        duration: 'Client',
    },
    {
        id: 'cl-002',
        platform: 'clients',
        title: 'Angelica — Voice AI Receptionist',
        description: 'Voice AI receptionist for ServiceMaxPro (home services). Retell AI, Cal.com v2 booking, Twilio SMS, Gmail — full post-call automation.',
        frontTexture: '/textures/studio/tv_cl-002.webp',
        paintedFrontTexture: '/textures/studio/tv_cl-002_painted.webp',
        thumbnail: null,
        url: 'https://www.linkedin.com/in/muhammad-umer-1bb52326b',
        date: '2026-02-15',
        views: 'Retell',
        duration: 'Client',
    },
    {
        id: 'cl-003',
        platform: 'clients',
        title: 'Gym Reinforcements — QA Automation',
        description: 'Gym franchise call QA system. Twilio call recordings → OpenAI Whisper transcription → GPT-4o compliance analysis → Gmail + Slack alerts.',
        frontTexture: '/textures/studio/tv_cl-003.webp',
        paintedFrontTexture: '/textures/studio/tv_cl-003_painted.webp',
        thumbnail: null,
        url: 'https://www.linkedin.com/in/muhammad-umer-1bb52326b',
        date: '2026-01-20',
        views: 'Whisper',
        duration: 'Client',
    },
    {
        id: 'cl-004',
        platform: 'clients',
        title: 'Mano Swartz Furs — Voice AI Sales',
        description: 'Retell AI inbound Voice AI agent for a fur coat sales business. Natural conversation, lead qualification, appointment booking.',
        frontTexture: '/textures/studio/tv_cl-004.webp',
        paintedFrontTexture: '/textures/studio/tv_cl-004_painted.webp',
        thumbnail: null,
        url: 'https://www.linkedin.com/in/muhammad-umer-1bb52326b',
        date: '2025-12-15',
        views: 'Retell',
        duration: 'Client',
    },

    // ============ GITHUB PROJECTS (Desktop Monitors) ============
    {
        id: 'gh-001',
        platform: 'github',
        title: 'PhishXplain — AI Phishing Detection',
        description: 'AI phishing detection system with SHAP-driven explainability. Deployed on HuggingFace Spaces. IEEE-format research paper.',
        frontTexture: '/textures/studio/monitor_gh-001.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-001_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/PhishXplain',
        date: '2026-05-06',
        readTime: 'Python',
    },
    {
        id: 'gh-002',
        platform: 'github',
        title: 'SurveilX — AI Surveillance Platform',
        description: 'Multi-camera anomaly detection using YOLOv8 + CLIP visual prompting. Natural language video search with H.264 clip generation.',
        frontTexture: '/textures/studio/monitor_gh-002.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-002_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/SurveilX',
        date: '2025-10-27',
        readTime: 'Python',
    },
    {
        id: 'gh-003',
        platform: 'github',
        title: 'Voyant Travel — Multi-Agent AI Planner',
        description: '5 specialized AI agents orchestrated by a Meta-Agent using CrewAI and Gemini. Complete travel itineraries with flights, hotels, activities.',
        frontTexture: '/textures/studio/monitor_gh-003.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-003_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/Voyant-Travel-Planner',
        date: '2025-11-21',
        readTime: 'Python',
    },
    {
        id: 'gh-004',
        platform: 'github',
        title: 'MCP Agentic AI — Chat Agent',
        description: 'Interactive chat agent with MCP servers for web search & browser control. Built with LangChain and Gemini.',
        frontTexture: '/textures/studio/monitor_gh-004.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-004_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/MCP_agentic_AI',
        date: '2025-06-27',
        readTime: 'Python',
    },
    {
        id: 'gh-005',
        platform: 'github',
        title: 'Story2Audio — AI Text-to-Speech',
        description: 'Converting stories into lifelike narrations using the Dia Model with gRPC streaming. Full audio pipeline.',
        frontTexture: '/textures/studio/monitor_gh-005.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-005_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/Story2Audio',
        date: '2025-05-09',
        readTime: 'Python',
    },
    {
        id: 'gh-006',
        platform: 'github',
        title: 'PDF Assistant — RAG Chatbot',
        description: 'AI-powered PDF analysis chatbot using RAG pipeline. Upload PDFs, ask questions, get accurate answers with citations.',
        frontTexture: '/textures/studio/monitor_gh-006.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-006_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/Pdf_assistant',
        date: '2025-06-15',
        readTime: 'Python',
    },
    {
        id: 'gh-007',
        platform: 'github',
        title: 'Excel Chatbot — Data Q&A',
        description: 'Natural language interface for Excel data analysis. Ask questions about your spreadsheets in plain English.',
        frontTexture: '/textures/studio/monitor_gh-007.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-007_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/Excel-Chatbot',
        date: '2024-08-14',
        readTime: 'Python',
    },
    {
        id: 'gh-008',
        platform: 'github',
        title: 'AdversaryGuard — AI Security',
        description: 'Adversarial attack detection and defense for ML models. FGSM implementation and robust model training.',
        frontTexture: '/textures/studio/monitor_gh-008.webp',
        paintedFrontTexture: '/textures/studio/monitor_gh-008_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321/adversaryguard',
        date: '2025-09-19',
        readTime: 'Python',
    },

    // ============ SKILLS (Phone Screens) ============
    {
        id: 'sk-001',
        platform: 'skills',
        title: 'Voice AI 🎙️',
        description: 'Retell AI, VAPI, ElevenLabs, Twilio, OpenAI Whisper, Cal.com',
        frontTexture: '/textures/studio/phone_sk-001.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-001_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-05-01',
        views: 'Core',
        likes: 'Skill',
    },
    {
        id: 'sk-002',
        platform: 'skills',
        title: 'n8n Automation ⚡',
        description: 'Multi-workflow pipelines, HubSpot, HeyReach, Instantly, Claude AI classification',
        frontTexture: '/textures/studio/phone_sk-002.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-002_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-04-25',
        views: 'n8n',
        likes: 'Expert',
    },
    {
        id: 'sk-003',
        platform: 'skills',
        title: 'LLMs & AI 🧠',
        description: 'GPT-4o, Claude 3, Gemini 2.0, LangChain, CrewAI, HuggingFace',
        frontTexture: '/textures/studio/phone_sk-003.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-003_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-04-15',
        views: 'LLMs',
        likes: 'RAG',
    },
    {
        id: 'sk-004',
        platform: 'skills',
        title: 'Python & FastAPI 🐍',
        description: 'Backend services, REST APIs, async processing, Docker deployments',
        frontTexture: '/textures/studio/phone_sk-004.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-004_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-04-01',
        views: 'FastAPI',
        likes: 'Docker',
    },
    {
        id: 'sk-005',
        platform: 'skills',
        title: 'Computer Vision 👁️',
        description: 'YOLOv8, CLIP, OpenCV — real-time object detection & visual search',
        frontTexture: '/textures/studio/phone_sk-005.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-005_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-03-20',
        views: 'YOLO',
        likes: 'CLIP',
    },
    {
        id: 'sk-006',
        platform: 'skills',
        title: 'RAG Systems 📚',
        description: 'Retrieval-augmented generation with vector databases, embeddings, LangChain pipelines',
        frontTexture: '/textures/studio/phone_sk-006.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-006_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-03-10',
        views: 'Pinecone',
        likes: 'Chroma',
    },
    {
        id: 'sk-007',
        platform: 'skills',
        title: 'CRM & Sales 📊',
        description: 'HubSpot, HeyReach, Instantly — outreach, deal tracking, lead management',
        frontTexture: '/textures/studio/phone_sk-007.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-007_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-02-28',
        views: 'HubSpot',
        likes: 'CRM',
    },
    {
        id: 'sk-008',
        platform: 'skills',
        title: 'Agentic AI 🤖',
        description: 'CrewAI multi-agent systems, MCP servers, autonomous tool-using agents',
        frontTexture: '/textures/studio/phone_sk-008.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-008_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-02-15',
        views: 'CrewAI',
        likes: 'MCP',
    },
    {
        id: 'sk-009',
        platform: 'skills',
        title: 'AI Security 🛡️',
        description: 'FGSM attacks, adversarial robustness, SHAP explainability, model hardening',
        frontTexture: '/textures/studio/phone_sk-009.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-009_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-02-01',
        views: 'SHAP',
        likes: 'FGSM',
    },
    {
        id: 'sk-010',
        platform: 'skills',
        title: 'React & Node.js 💻',
        description: 'Full-stack web development, REST APIs, real-time dashboards',
        frontTexture: '/textures/studio/phone_sk-010.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-010_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-01-20',
        views: 'React',
        likes: 'Node',
    },
    {
        id: 'sk-011',
        platform: 'skills',
        title: 'DevOps & Cloud ☁️',
        description: 'Docker, Git, CI/CD, HuggingFace Spaces, Vercel deployments',
        frontTexture: '/textures/studio/phone_sk-011.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-011_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2026-01-10',
        views: 'Docker',
        likes: 'Git',
    },
    {
        id: 'sk-012',
        platform: 'skills',
        title: 'Prompt Engineering ✍️',
        description: 'Advanced prompting for GPT-4, Claude, Gemini — system prompts, chain-of-thought',
        frontTexture: '/textures/studio/phone_sk-012.webp',
        paintedFrontTexture: '/textures/studio/phone_sk-012_painted.webp',
        thumbnail: null,
        url: 'https://github.com/Kaizer321',
        date: '2025-12-25',
        views: 'GPT-4',
        likes: 'Claude',
    },
];

// Helper to get content by platform
export const getContentByPlatform = (platform) => {
    if (platform === 'all') return CONTENT_DATA;
    return CONTENT_DATA.filter(item => item.platform === platform);
};

// Get latest content (for "On Air" indicator)
export const getLatestContent = () => {
    return [...CONTENT_DATA].sort((a, b) => new Date(b.date) - new Date(a.date))[0];
};
